/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.kris.apiai.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ApiAiData service. Represents a row in the &quot;APIAI_ApiAiData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.kris.apiai.model.impl.ApiAiDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.kris.apiai.model.impl.ApiAiDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApiAiData
 * @generated
 */
@ProviderType
public interface ApiAiDataModel
	extends BaseModel<ApiAiData>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a api ai data model instance should use the {@link ApiAiData} interface instead.
	 */

	/**
	 * Returns the primary key of this api ai data.
	 *
	 * @return the primary key of this api ai data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this api ai data.
	 *
	 * @param primaryKey the primary key of this api ai data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this api ai data.
	 *
	 * @return the uuid of this api ai data
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this api ai data.
	 *
	 * @param uuid the uuid of this api ai data
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the api ai data ID of this api ai data.
	 *
	 * @return the api ai data ID of this api ai data
	 */
	public long getApiAiDataId();

	/**
	 * Sets the api ai data ID of this api ai data.
	 *
	 * @param apiAiDataId the api ai data ID of this api ai data
	 */
	public void setApiAiDataId(long apiAiDataId);

	/**
	 * Returns the group ID of this api ai data.
	 *
	 * @return the group ID of this api ai data
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this api ai data.
	 *
	 * @param groupId the group ID of this api ai data
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this api ai data.
	 *
	 * @return the company ID of this api ai data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this api ai data.
	 *
	 * @param companyId the company ID of this api ai data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this api ai data.
	 *
	 * @return the user ID of this api ai data
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this api ai data.
	 *
	 * @param userId the user ID of this api ai data
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this api ai data.
	 *
	 * @return the user uuid of this api ai data
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this api ai data.
	 *
	 * @param userUuid the user uuid of this api ai data
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this api ai data.
	 *
	 * @return the user name of this api ai data
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this api ai data.
	 *
	 * @param userName the user name of this api ai data
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this api ai data.
	 *
	 * @return the create date of this api ai data
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this api ai data.
	 *
	 * @param createDate the create date of this api ai data
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this api ai data.
	 *
	 * @return the modified date of this api ai data
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this api ai data.
	 *
	 * @param modifiedDate the modified date of this api ai data
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this api ai data.
	 *
	 * @return the type of this api ai data
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this api ai data.
	 *
	 * @param type the type of this api ai data
	 */
	public void setType(String type);

	/**
	 * Returns the result of this api ai data.
	 *
	 * @return the result of this api ai data
	 */
	@AutoEscape
	public String getResult();

	/**
	 * Sets the result of this api ai data.
	 *
	 * @param result the result of this api ai data
	 */
	public void setResult(String result);

	/**
	 * Returns the action of this api ai data.
	 *
	 * @return the action of this api ai data
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this api ai data.
	 *
	 * @param action the action of this api ai data
	 */
	public void setAction(String action);

	/**
	 * Returns the fulfillment of this api ai data.
	 *
	 * @return the fulfillment of this api ai data
	 */
	@AutoEscape
	public String getFulfillment();

	/**
	 * Sets the fulfillment of this api ai data.
	 *
	 * @param fulfillment the fulfillment of this api ai data
	 */
	public void setFulfillment(String fulfillment);

	/**
	 * Returns the speech of this api ai data.
	 *
	 * @return the speech of this api ai data
	 */
	@AutoEscape
	public String getSpeech();

	/**
	 * Sets the speech of this api ai data.
	 *
	 * @param speech the speech of this api ai data
	 */
	public void setSpeech(String speech);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ApiAiData apiAiData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ApiAiData> toCacheModel();

	@Override
	public ApiAiData toEscapedModel();

	@Override
	public ApiAiData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}